### Home route
GET https://webservices-6cvg.onrender.com/

### Get all contacts
GET https://webservices-6cvg.onrender.com/contacts

### Get single contact by ID
GET https://webservices-6cvg.onrender.com/contacts/69fc6a01f92c8fb14defb02a

### Create a new contact
POST https://webservices-6cvg.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Thomas",
  "email": "johnthomas@gmail.com",
  "favoriteColor": "Blue",
  "birthday": "1990-05-15"
}

### Update a contact
PUT https://webservices-6cvg.onrender.com/contacts/69fc6a01f92c8fb14defb02a
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Nambogwe",
  "email": "janenambogwe@gmail.com",
  "favoriteColor": "Green",
  "birthday": "1992-03-20"
}

### Delete a contact
DELETE https://webservices-6cvg.onrender.com/contacts/69fc6a01f92c8fb14defb02a